"""
Quick Start Script - Interactive setup guide
Run this to set up your Mimi memory system step by step
"""

import os
import sys
import subprocess

def print_header(text):
    print("\n" + "="*70)
    print(text)
    print("="*70 + "\n")

def print_step(number, text):
    print(f"\n{'─'*70}")
    print(f"STEP {number}: {text}")
    print('─'*70 + "\n")

def check_file_exists(filepath):
    """Check if a file exists"""
    return os.path.exists(filepath)

def create_env_file():
    """Guide user through creating .env file"""
    print_step(1, "Create .env File")
    
    if check_file_exists(".env"):
        print("✅ .env file already exists")
        overwrite = input("Do you want to recreate it? (y/n): ").lower()
        if overwrite != 'y':
            return True
    
    print("\nLet's create your .env file with the required configuration.")
    print("\nYou'll need:")
    print("  1. MongoDB connection string (local or Atlas)")
    print("  2. OpenAI or Anthropic API key")
    print("  3. A secret key for JWT authentication")
    
    print("\n" + "-"*70)
    
    # Get MongoDB URI
    print("\n📦 MongoDB Configuration")
    print("Press Enter to use default (mongodb://localhost:27017/)")
    print("Or enter your MongoDB Atlas URI:")
    mongodb_uri = input("> ").strip()
    if not mongodb_uri:
        mongodb_uri = "mongodb://localhost:27017/"
    
    # Get API keys
    print("\n🤖 LLM API Keys")
    print("Enter your OpenAI API key (or press Enter to skip):")
    openai_key = input("> ").strip()
    
    anthropic_key = ""
    if not openai_key:
        print("\nEnter your Anthropic API key (required if no OpenAI key):")
        anthropic_key = input("> ").strip()
    
    if not openai_key and not anthropic_key:
        print("\n❌ Error: At least one API key is required!")
        print("Get keys from:")
        print("  - OpenAI: https://platform.openai.com/api-keys")
        print("  - Anthropic: https://console.anthropic.com/")
        return False
    
    # Get secret key
    print("\n🔐 Security Configuration")
    print("Enter a secret key for JWT (or press Enter to generate one):")
    secret = input("> ").strip()
    if not secret:
        import secrets
        secret = secrets.token_urlsafe(32)
        print(f"Generated secret key: {secret[:20]}...")
    
    # Write .env file
    env_content = f"""# Mimi AI Configuration
# Generated by quick_start.py

# MongoDB
MONGODB_URI={mongodb_uri}

# LLM API Keys
"""
    
    if openai_key:
        env_content += f"OPENAI_API_KEY={openai_key}\n"
    
    if anthropic_key:
        env_content += f"ANTHROPIC_API_KEY={anthropic_key}\n"
    
    env_content += f"""
# JWT Secret
SECRET={secret}

# Basic Memory (Default)
USE_ADVANCED_MEMORY=false

# Advanced Memory (Uncomment when ready)
# REDIS_URL=redis://localhost:6379/0
# DATABASE_URL=postgresql://postgres:password@localhost:5432/mimidb
# QDRANT_URL=http://localhost:6333
"""
    
    with open(".env", "w") as f:
        f.write(env_content)
    
    print("\n✅ .env file created successfully!")
    return True

def install_dependencies():
    """Install Python dependencies"""
    print_step(2, "Install Dependencies")
    
    print("Installing required Python packages...")
    print("This may take a few minutes...\n")
    
    try:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-r", "requirements.txt"])
        print("\n✅ Dependencies installed successfully!")
        return True
    except subprocess.CalledProcessError:
        print("\n❌ Failed to install dependencies")
        print("Try manually: pip install -r requirements.txt")
        return False

def test_setup():
    """Run basic tests"""
    print_step(3, "Test Configuration")
    
    print("Running configuration tests...\n")
    
    try:
        # Import test to check dependencies
        from dotenv import load_dotenv
        load_dotenv()
        
        # Check .env loaded
        mongodb_uri = os.environ.get("MONGODB_URI")
        openai_key = os.environ.get("OPENAI_API_KEY")
        anthropic_key = os.environ.get("ANTHROPIC_API_KEY")
        
        print(f"MongoDB URI: {'✅ Set' if mongodb_uri else '❌ Missing'}")
        print(f"OpenAI Key: {'✅ Set' if openai_key else '❌ Missing'}")
        print(f"Anthropic Key: {'✅ Set' if anthropic_key else '⚠️  Not set (optional)'}")
        
        if not mongodb_uri or (not openai_key and not anthropic_key):
            print("\n❌ Configuration incomplete")
            return False
        
        print("\n✅ Configuration looks good!")
        return True
        
    except ImportError as e:
        print(f"❌ Import error: {e}")
        print("Run: pip install -r requirements.txt")
        return False

def run_tests():
    """Run test scripts"""
    print_step(4, "Run Tests")
    
    print("Would you like to run the test suite?")
    print("This will:")
    print("  - Test MongoDB connection")
    print("  - Verify API keys")
    print("  - Test basic memory functionality")
    
    run = input("\nRun tests now? (y/n): ").lower()
    if run != 'y':
        print("\nSkipping tests. You can run them later with:")
        print("  python test_api.py")
        return True
    
    print("\nRunning API tests...")
    try:
        subprocess.check_call([sys.executable, "test_api.py"])
        return True
    except subprocess.CalledProcessError:
        print("\n⚠️  Some tests failed, but you can still continue")
        return True
    except FileNotFoundError:
        print("\n⚠️  test_api.py not found")
        return True

def show_next_steps():
    """Show what to do next"""
    print_header("🎉 Setup Complete!")
    
    print("Your Mimi AI is ready to use!\n")
    
    print("Next Steps:\n")
    
    print("1. Start the Flask application:")
    print("   python app.py")
    print()
    
    print("2. Test the memory system:")
    print("   python test_live_memory.py")
    print()
    
    print("3. (Optional) Set up advanced memory:")
    print("   - Install Docker Desktop")
    print("   - Run: docker run -d -p 6379:6379 redis:7-alpine")
    print("   - Run: docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=pass postgres:15-alpine")
    print("   - Run: docker run -d -p 6333:6333 qdrant/qdrant")
    print("   - Update .env: USE_ADVANCED_MEMORY=true")
    print("   - Test: python test_advanced_memory.py")
    print()
    
    print("4. Read the documentation:")
    print("   - SETUP_GUIDE.md - Detailed setup instructions")
    print("   - QUICK_START_MEMORY.md - Quick reference")
    print("   - ADVANCED_MEMORY_SYSTEM.md - Advanced features")
    print()
    
    print("Need help? Check the documentation files or run:")
    print("   python test_api.py    # Test API configuration")
    print("   python test_memory.py # Test basic memory")
    print()

def main():
    """Main setup flow"""
    print("""
╔══════════════════════════════════════════════════════════════════════╗
║                                                                      ║
║                    MIMI AI QUICK START SETUP                         ║
║                                                                      ║
║  This will guide you through setting up your Mimi AI system         ║
║  with conversation memory capabilities                               ║
║                                                                      ║
╚══════════════════════════════════════════════════════════════════════╝
    """)
    
    print("Press Ctrl+C at any time to exit\n")
    
    try:
        # Check if we're in the right directory
        if not check_file_exists("app.py"):
            print("❌ Error: app.py not found!")
            print("Make sure you're in the mimiplay project directory")
            return
        
        # Step 1: Create .env
        if not create_env_file():
            print("\n❌ Setup failed at step 1")
            return
        
        # Step 2: Install dependencies
        install = input("\nInstall Python dependencies now? (y/n): ").lower()
        if install == 'y':
            if not install_dependencies():
                print("\n⚠️  Continuing anyway...")
        else:
            print("\nSkipped. Install later with: pip install -r requirements.txt")
        
        # Step 3: Test configuration
        if not test_setup():
            print("\n⚠️  Configuration issues detected")
            cont = input("Continue anyway? (y/n): ").lower()
            if cont != 'y':
                return
        
        # Step 4: Run tests
        run_tests()
        
        # Show next steps
        show_next_steps()
        
    except KeyboardInterrupt:
        print("\n\n⚠️  Setup interrupted by user")
        print("You can run this script again to continue setup")
    except Exception as e:
        print(f"\n❌ Setup failed: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    main()
