apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # Container name on mimi-network Docker bridge
    url: http://mimi-prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: "15s"
